import {useEffect,useRef,useState,type FormEvent} from 'react';
import {api} from '../../services/api';
import RentalHistory from './RentalHistory';
import {errorMessage,money,post} from './api';
interface Tool {id:number;nome:string;quantidade:number;disponivel:number;diaria:number;status:string}
export default function RentalAdmin({onHome,onLogin}:{onHome:()=>void;onLogin:()=>void}){
 const [tools,setTools]=useState<Tool[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 const lock=useRef(false);
 useEffect(()=>{const c=new AbortController();api.get<Tool[]>('/locacao/admin/ferramentas',{signal:c.signal}).then(r=>setTools(r.data)).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[version]);
 async function execute(path:string,data:unknown,done?:()=>void){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await post(path,data);setMessage('Alteração salva.');done?.();setVersion(n=>n+1);}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}}
 function create(e:FormEvent<HTMLFormElement>,kit:boolean){e.preventDefault();const form=e.currentTarget,d=new FormData(form);const common={nome:String(d.get('nome')),descricao:String(d.get('descricao')),diaria:Number(d.get('diaria'))};const componentes=tools.map(t=>({id:t.id,quantidade:Number(d.get('tool'+t.id))})).filter(t=>t.quantidade>0);if(kit&&!componentes.length){setError('Inclua pelo menos uma ferramenta no kit.');return;}void execute(kit?'/admin/kits':'/admin/ferramentas',kit?{...common,componentes}:{...common,quantidade:Number(d.get('quantidade'))},()=>form.reset());}
 return <section className="th-wizard th-workspace"><button className="th-link" onClick={onHome}>Voltar à Home</button><h1>Administração dos aluguéis</h1><p>Cadastre equipamentos do TechHelp, informe as taxas conforme o endereço e acompanhe retiradas e devoluções.</p>
 {loading&&<p role="status">Carregando estoque…</p>}{error&&<div role="alert"><p>{error}</p><button className="th-link" onClick={()=>{setError('');setVersion(n=>n+1);}}>Atualizar</button> <button className="th-link" onClick={onLogin}>Entrar novamente</button></div>}{message&&<p role="status">{message}</p>}
 <div className="th-rental-grid">{[false,true].map(kit=><form className="th-panel th-tech-card" key={String(kit)} onSubmit={e=>create(e,kit)}><h2>{kit?'Montar kit':'Cadastrar ferramenta'}</h2><fieldset className="th-rental-form" disabled={busy||loading}><label className="th-label">Nome<input className="th-field" name="nome" required maxLength={140}/></label><label className="th-label">Descrição<textarea className="th-field" name="descricao" maxLength={3000}/></label><label className="th-label">Diária (R$)<input className="th-field" name="diaria" type="number" min="0.01" max="9999999999.99" step="0.01" required/></label>{kit?<><p>Unidades de cada ferramenta por kit. Use zero para não incluir.</p>{tools.map(t=><label className="th-label" key={t.id}>{t.nome}<input className="th-field" name={'tool'+t.id} type="number" min="0" max={Math.min(1000,t.quantidade)} defaultValue="0"/></label>)}</>:<label className="th-label">Quantidade total<input className="th-field" name="quantidade" type="number" min="1" max="10000" required/></label>}<button className="th-button" disabled={kit&&!tools.length}>{busy?'Salvando…':kit?'Cadastrar kit':'Cadastrar ferramenta'}</button></fieldset></form>)}</div>
 <h2>Estoque de ferramentas</h2>{!loading&&!tools.length&&<p>Nenhuma ferramenta cadastrada.</p>}<div className="th-rental-grid">{tools.map(t=><article className="th-panel th-tech-card" key={t.id}><h3>{t.nome}</h3><p>{t.disponivel} disponíveis de {t.quantidade} · {money(t.diaria)} / diária</p><label className="th-label">Situação<select className="th-field" value={t.status} disabled={busy} onChange={e=>void execute(`/admin/ferramentas/${t.id}/status`,{status:e.target.value})}><option value="DISPONIVEL">Disponível</option><option value="MANUTENCAO">Em manutenção</option><option value="INATIVA">Inativa</option></select></label></article>)}</div>
 <RentalHistory admin onLogin={onLogin}/></section>;
}
